name: tutorials
channels:
- conda-forge
dependencies:
- python=3.9
- pangeo-notebook
- xarray=0.21
- awscli~=1.20
- matplotlib-base~=3.4
- ipyleaflet=0.14
- shapely=1.7
- geopandas=0.10
- h5py=2.10
- h5netcdf~=0.11
- netcdf4~=1.5
- geopy~=2.2
- pyresample~=1.22
- earthdata~=0.2.2
- fiona~=1.8
- gql=2.0.0
- zarr=2.10
- ipympl=0.6
- descartes~=1.1
- rasterio~=1.2
- plotly~=5.4
- joblib~=1.1
- cartopy~=0.20
- pystac-client~=0.3
- s3fs~=2022.2
- vaex
- tqdm
- intake-xarray
- intake-stac
- jupyter-offlinenotebook
- sidecar
- icepyx
- geoviews
- pip
- pip:
  - python-cmr
